function Hd = chevFilter(Fpass1, Fpass2)
%TESTFILTERCHEV Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 11-Jul-2022 01:26:17

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N      = 12;    % Order
%Fpass1 = 1000;  % First Passband Frequency
%Fpass2 = 2760;  % Second Passband Frequency
Apass  = 1;     % Passband Ripple (dB)

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
Hd = design(h, 'cheby1');
